server:
  port: 8084

spring:
  application:
    name: auth-service

chitchat:
  jwt:
    base64-secret: cHJldmlvdXNjb25zdGFudGx5ZGl2aWRlYmFzZXBsYWludHJhdmVsZGlzaHdyYXBwZWQ=
    access-token-validity-in-seconds: 86400
    refresh-token-validity-in-seconds: 86400