server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
        
        - id: chat-service
          uri: http://localhost:8083
          predicates:
            - Path=/chat/**
        
        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/notification/**