server:
  port: 8888

spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: MjbO8FU02FSIXzP8FwYoz5H7fxPWoXMPxyKjDBBMAYA=
  cloud:
    gateway:
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins:
                - "http://localhost:5172"
                - "http://localhost:5173"
                - "http://127.0.0.1:5173"
              allowedMethods: "*"
              allowedHeaders: "*"
              allowCredentials: true

      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<path>.*), /$\{path}

        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}

        - id: chat-service
          uri: http://chat-service:8082
          predicates:
            - Path=/chat-service/**
          filters:
            - RewritePath=/chat-service/(?<path>.*), /$\{path}

        - id: chat-service-ws
          uri: ws://chat-service:8082
          predicates:
            - Path=/chat-service/ws/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: http://notification-service:8083
          predicates:
            - Path=/notification-service/**
          filters:
            - RewritePath=/notification-service/(?<path>.*), /$\{path}
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG


chitchat:
  jwt:
    base64-secret: MjbO8FU02FSIXzP8FwYoz5H7fxPWoXMPxyKjDBBMAYA=
    access-token-validity-in-seconds: 86400
    refresh-token-validity-in-seconds: 86400