server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LucPham2004/ChitChat-config-repo.git
          default-label: main
  profiles:
    active: git

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
